config/routes.rb
Rails.application.routes.draw do
 
  resources :bottles
  resources :pages, :only => [:home, :idea]
  
  post 'bottles/index'

  resources :basket_items
  resources :basket
  get 'cart', to: 'cart#show'
  get 'bottles/index'  
  get 'pages/idea'

  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
 
  
  resources :wallets
  resource :wallet
    resolve('Wallet') {[:wallet]}

  patch 'wallet/:id', to: 'wallets#add_money' 

  resource :wallet do
    member do
      get 'add_money'
    end
  end


  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
 
  root :to=>"pages#home"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/basket.rb
class Basket < ApplicationRecord
    has_many :basket_items
    before_save :set_subtotal

    def subtotal
        basket_items.collect {|basket_item| basket_item.valid? ? basket_item.unit_price * basket_item.quantity : 0}.sum
    end

    private
    def set_subtotal
        self[:subtotal] = subtotal
    end
end

app/models/basket_item.rb
class BasketItem < ApplicationRecord
  belongs_to :bottle
  belongs_to :basket
  before_save :set_unit_price
  before_save :set_total


  def unit_price
    # If there is a record
    if persisted?
      self[:unit_price]
    else
      bottle.price
    end
  end

  def total
    return unit_price * quantity
  end

  private
  def set_unit_price
    self[:unit_price] = unit_price
  end

  def set_total
    self[:total] = total * quantity
  end

end

app/models/bottle.rb
class Bottle < ApplicationRecord

validates :material, :presence => true
validates :size, :presence => true
validates :price, :presence => true

has_one_attached :image, dependent: :destroy
has_many :basket_items

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :wallet

  after_create do |user|
    user.create_wallet
  end
  

end

app/models/wallet.rb
class Wallet < ApplicationRecord

    belongs_to :user 
    has_and_belongs_to_many :carts

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include ApplicationHelper
end

app/controllers/basket_controller.rb
class BasketController < ApplicationController
 

end

app/controllers/basket_items_controller.rb
class BasketItemsController < ApplicationController
  before_action :set_basket
  before_action :authenticate_user!, except: [:create, :destroy]
  
  def create
    @basket_item = @basket.basket_items.new(basket_params)
    @basket.save
    session[:basket_id] = @basket.id
    redirect_to "/cart"
  end

  def update
    @basket_item = @basket.basket_items.find(params[:id])
    @basket_item.update(basket_params)
    @basket_items = current_basket.basket_items
    redirect_to "/cart"
  end

  def destroy
    @basket_item = @basket.basket_items.find(params[:id])
    @basket_item.destroy
    @basket_items = current_basket.basket_items
    redirect_to "/cart"
  end

  private
  def basket_params
    params.require(:basket_item).permit(:bottle_id, :quantity)
  end
  
  def set_basket
    @basket = current_basket
  end


end

app/controllers/bottles_controller.rb
class BottlesController < ApplicationController
  before_action :set_bottle, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :check_logged_in, :only => [:new, :create, :destroy]

  # GET /bottles or /bottles.json
  def index
    @bottles = Bottle.all
    @basket_item = current_basket.basket_items.new
  end

  # GET /bottles/1 or /bottles/1.json
  def show
  end

  # GET /bottles/new
  def new
    @bottle = Bottle.new
  end

  # GET /bottles/1/edit
  def edit
  end

  # POST /bottles or /bottles.json
  def create
    @bottle = Bottle.new(bottle_params)

    respond_to do |format|
      if @bottle.save
        format.html { redirect_to @bottle, notice: "Bottle was successfully created." }
        format.json { render :show, status: :created, location: @bottle }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @bottle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bottles/1 or /bottles/1.json
  def update
    respond_to do |format|
      if @bottle.update(bottle_params)
        format.html { redirect_to @bottle, notice: "Bottle was successfully updated." }
        format.json { render :show, status: :ok, location: @bottle }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @bottle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bottles/1 or /bottles/1.json
  def destroy
    @bottle.destroy
    respond_to do |format|
      format.html { redirect_to bottles_url, notice: "Bottle was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def check_logged_in
    authenticate_or_request_with_http_basic("Ads") do |email, password|
    email == "admin@admin.pl" && password == "admins"
    end
  end

  def authorize
    redirect_to '/login' unless current_user
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bottle
      @bottle = Bottle.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def bottle_params
      params.require(:bottle).permit(:material, :size, :price, :id, :image)
    end

end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :authenticate_user!

  def show
      @basket_items = current_basket.basket_items
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    render 'pages/home'
  end

  def idea
    render 'pages/idea'
  end

end

app/controllers/wallets_controller.rb
class WalletsController < ApplicationController
  before_action :authenticate_user!


  def show
  end


  def create
    wallet_params = params.require(wallet).permit(:user_id, :total_amount, :carts)
    @wallet = Wallet.new(wallet_params)
  end


  def add_money
    @wallet = current_user.wallet
    @wallet.update(total_amount: @wallet.total_amount + current_basket.subtotal)
    # @wallet.carts << current_basket.subtotal
    session.delete(:basket_id)
    redirect_to "/wallet" 
  end

private
  def wallet_params
    params.require(:wallet).permit(:user_id, :total_amount, :carts)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
Rack::MiniProfiler.config.position = 'bottom-right'
Rack::MiniProfiler.config.start_hidden = true

    def current_basket
        # Use Find by id to avoid potential errors
        if Basket.find_by_id(session[:basket_id]).nil?
            Basket.new
        else
            Basket.find_by_id(session[:basket_id])
        end
    end


end

app/helpers/basket_helper.rb
module BasketHelper
end

app/helpers/basket_items_helper.rb
module BasketItemsHelper
end

app/helpers/bottles_helper.rb
module BottlesHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/wallets_helper.rb
module WalletsHelper
end

app/views/basket/show.html.erb
<div id="basket-item">
<%= render "basket_items" %>
</div>

app/views/basket_items/create.html.erb
<script>
$("#cart-item").html("<%= render 'cart/cart' %>");
</script>

app/views/basket_items/destroy.html.erb
<script>
$("#cart").html("<%= j render 'cart/cart' %>");
$("#cart_item").html("<%= j render 'cart/cart_items' %>");
</script>

app/views/basket_items/update.html.erb
<script>
$("#cart").html("<%= j render 'cart/cart' %>");
$("#cart_item").html("<%= j render 'cart/cart_items' %>");
</script>

app/views/bottles/_form.html.erb
<%= form_with(model: bottle) do |form| %>
  <% if bottle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(bottle.errors.count, "error") %> prohibited this bottle from being saved:</h2>

      <ul>
        <% bottle.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :material %>
    <%= form.text_field :material %>
  </div>

  <div class="field">
    <%= form.label :size %>
    <%= form.text_field :size %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="actions btn">
    <%= form.submit %>
  </div>

<% end %>

app/views/bottles/edit.html.erb
<h1>Edycja butelki</h1>

<%= render 'form', bottle: @bottle %>

<div class="link"><%= link_to 'Pokaż', @bottle %></div>
<div class="link"><%= link_to 'Powrót', bottles_path %></div>

app/views/bottles/index.html.erb
<p id="notice"><%= notice %></p>

<h4 class="subtitle-2">Butelki, które możesz zwrócić</h4>

  <div class="row">
    <% @bottles.each do |bottle| %>
      <div class="bottle-wrapper">
        <div class="img-btl"><%= image_tag(bottle.image, style: 'background-color:var(--main-green)') %></div>
        <p><%= bottle.material %></p>
        <p><%= bottle.size %></p>
        <p>Cena: <%= bottle.price %> zł</p>
         <%= form_with model: @basket_item do |f| %>
         <%= f.hidden_field :bottle_id, value: bottle.id %>
         <div class="field"><%= f.number_field :quantity, value: 0, min: 1 %> </div>
         <div class="btn"><%= f.submit "Dodaj do koszyka" %></div>
         <% end  %>

        <div class="link"><%= link_to 'Pokaż', bottle %></div>
        <div class="link"><%= link_to 'Edytuj', edit_bottle_path(bottle) %></div>
        <div class="link"><%= link_to 'Usuń', bottle, method: :delete, data: { confirm: 'Jesteś pewnien?' } %></div>
      </div>
    <% end %>
  
  </div>

<br>
<div class="link"><%= link_to 'Dodaj butelkę', new_bottle_path %></div>
<div class="link"><%= link_to 'Powrót', root_path %></div>

app/views/bottles/new.html.erb
<h1>Nowa butelka</h1>

<%= render 'form', bottle: @bottle %>

<%= link_to 'Powrót', bottles_path %>

app/views/bottles/show.html.erb
<p id="notice"><%= notice %></p>
  
<div class="img-btl"> 
  <%= image_tag(@bottle.image, style: 'background-color:var(--dark-green)') %>
</div>
<p>
  <strong>Materiał:</strong>
  <%= @bottle.material %>
</p>
<p>
  <strong>Rozmiar:</strong>
  <%= @bottle.size %>
</p>
<p>
  <strong>Cena:</strong>
  <%= @bottle.price %>
</p>


<div class="link"><%= link_to 'Edytuj', edit_bottle_path(@bottle) %></div>
<div class="link"><%= link_to 'Powrót', bottles_path %></div>

app/views/cart/_cart.html.erb
<%= link_to "#{current_basket.basket_items.size} zgromadzona kwota to #{current_basket.subtotal} zł", cart_path %>

app/views/cart/_cart_items.html.erb
<div class="cart">
<% @basket_items.each do |item| %>
<p><%= item.bottle.material%></p>
<p><%= item.bottle.size %></p>
<p><%= item.bottle.price %> zł</p>
<%= form_with model: item do |f| %>
<%= f.hidden_field :bottle_id, value: item.bottle.id %>
<%= f.number_field :quantity, value: item.quantity.to_i%>
<% end %>
<button><%= link_to "Usuń z koszyka", item, method: :delete %></button>
<p>Subtotal: <%= item.total %></p>
<% end %>
<div class="wallet">
<p><strong>W twoim koszyku obecnie jest: <%= current_basket.subtotal %> zł</strong></p>
<%= form_for current_user.wallet, url: add_money_wallet_path do |f| %>
</div>
<div class="btn add-to-wallet"> <%= f.submit "Dodaj całość do mojego portfela" %></div>
<%= session[:basket_id] %>
<% end %>

<%= link_to 'Powrót', bottles_path %>
</div>

app/views/cart/show.html.erb
<div id="cart-item">
<%= render 'cart_items' %>
</div>

app/views/layouts/_title.html.erb
<div class="title-card">
    <h1 class="title-text"><%= link_to 'Butelki zwrotne', root_path %></h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bottles</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@300;400;500;600;700&display=swap" rel="stylesheet"> 
  </head>

  <body>
    <main class="mx-auto main-container">

      <nav class="navbar-text">
        <%= link_to "", root_path, :class => 'navbar-link' %>
        <% if user_signed_in? %>
          Zalogowany jako <strong><%= current_user.email %></strong>.
          <%= link_to 'Edytuj profil', edit_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Wyloguj", destroy_user_session_path, method: :delete, :class => 'navbar-link' %> |
          <%= link_to "Mój portfel", wallet_path(:wallet_id), :class => 'navbar-link' %>
        <% else %>
          <%= link_to "Rejestracja", new_user_registration_path, :class => 'navbar-link' %> |
          <%= link_to "Zaloguj", new_user_session_path, :class => 'navbar-link' %>
        <% end %>
      </nav>

      <% if notice %>
        <p class="alert alert-success"><%= notice %></p>
      <% end %>
      <% if alert %>
        <p class="alert alert-danger"><%= alert %></p>
      <% end %>

 <div class="title-img">
    <div class="neon-btls">
    </div>
</div>
    <div class="main-title">
        <%= render "layouts/title" %>
    </div>

      <div class="content-wrapper">
        <%= yield %>
      </div>
    <footer><div>&copy; Agata Adamczewska 2021</div></footer> 
    </main>
  </body>
</html>

app/views/pages/home.html.erb
<div class="content-subtitles">    
    <div class="subtitle"><a href="pages/idea">Nasza idea - zobacz, dlaczego warto zwracać butelki</a></div>
    <div class="subtitle"><a href="bottles">Sprawdź, jakie butelki możesz zwrócić</a></div>
</div>

app/views/pages/idea.html.erb
<h4 class="subtitle-2">Nasza idea - mniej śmieci!</h4>
<p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure molestiae dolor voluptatum, neque aliquam dolore nobis! Quod, 
cupiditate. Veritatis aliquid nam adipisci veniam inventore neque eveniet odit animi harum rerum.Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure molestiae dolor voluptatum, neque aliquam dolore nobis! Quod, 
cupiditate. Veritatis aliquid nam adipisci veniam inventore neque eveniet odit animi harum rerum.Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure molestiae dolor voluptatum, neque aliquam dolore nobis! Quod, 
cupiditate. Veritatis aliquid nam adipisci veniam inventore neque eveniet odit animi harum rerum.Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure molestiae dolor voluptatum, neque aliquam dolore nobis! Quod, 
cupiditate. 
Veritatis aliquid nam adipisci veniam inventore neque eveniet odit animi harum rerum.Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure molestiae dolor voluptatum, neque aliquam dolore nobis! Quod, 
cupiditate. Veritatis aliquid nam adipisci veniam inventore neque eveniet odit animi harum rerum.Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure molestiae dolor voluptatum, neque aliquam dolore nobis! Quod, 
cupiditate. Veritatis aliquid nam adipisci veniam inventore neque eveniet odit animi harum rerum.Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure molestiae dolor voluptatum, neque aliquam dolore nobis! Quod, 
cupiditate. Veritatis aliquid nam adipisci veniam inventore neque eveniet odit animi harum rerum.Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure molestiae dolor voluptatum, neque aliquam dolore nobis! Quod, 
cupiditate. Veritatis aliquid nam adipisci veniam inventore neque eveniet odit animi harum rerum.Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure molestiae dolor voluptatum, neque aliquam dolore nobis! Quod, 
cupiditate. 
Veritatis aliquid nam adipisci veniam inventore neque eveniet odit animi harum rerum.Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure molestiae dolor voluptatum, neque aliquam dolore nobis! Quod, 
cupiditate. Veritatis aliquid nam adipisci veniam inventore neque eveniet odit animi harum rerum.Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure molestiae dolor voluptatum, neque aliquam dolore nobis! Quod, 
cupiditate. Veritatis aliquid nam adipisci veniam inventore neque eveniet odit animi harum rerum.Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure molestiae dolor voluptatum, neque aliquam dolore nobis! Quod, 
cupiditate. Veritatis aliquid nam adipisci veniam inventore neque eveniet odit animi harum rerum.Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure molestiae dolor voluptatum, neque aliquam dolore nobis! Quod, 
cupiditate. Veritatis aliquid nam adipisci veniam inventore neque eveniet odit animi harum rerum.Lorem ipsum dolor sit amet consectetur adipisicing elit. 
Iure molestiae dolor voluptatum, neque aliquam dolore nobis! Quod, 
cupiditate. Veritatis aliquid nam adipisci veniam inventore neque eveniet odit animi harum rerum.Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure molestiae dolor voluptatum, neque aliquam dolore nobis! Quod, 
cupiditate. Veritatis aliquid nam adipisci veniam inventore neque eveniet odit animi harum rerum.Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure molestiae dolor voluptatum, neque aliquam dolore nobis! Quod, 
cupiditate. Veritatis aliquid nam adipisci veniam inventore neque eveniet odit animi harum rerum.Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure molestiae dolor voluptatum, neque aliquam dolore nobis! Quod, 
cupiditate. Veritatis aliquid nam adipisci veniam inventore neque eveniet odit animi harum rerum.Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure molestiae dolor voluptatum, neque aliquam dolore nobis! Quod, 
cupiditate. Veritatis aliquid nam adipisci veniam inventore neque eveniet odit animi harum rerum.Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure molestiae dolor voluptatum, neque aliquam dolore nobis! Quod, 
cupiditate. Veritatis aliquid nam adipisci veniam inventore neque eveniet odit animi harum rerum.Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure molestiae dolor voluptatum, neque aliquam dolore nobis! Quod, 
cupiditate. Veritatis aliquid nam adipisci veniam inventore neque eveniet odit animi harum rerum.Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure molestiae dolor voluptatum, neque aliquam dolore nobis! Quod, 
cupiditate. Veritatis aliquid nam adipisci veniam inventore neque eveniet odit animi harum rerum.Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure molestiae dolor voluptatum, neque aliquam dolore nobis! Quod, 
cupiditate. Veritatis aliquid nam adipisci veniam inventore neque eveniet odit animi harum rerum.</p>
<%= link_to 'Back', root_path %>

app/views/wallets/show.html.erb
<div class="wallet">

<p id="notice"><%= notice %></p>

<h3>Obecnie masz w swoim portfelu: 
  <% @wallet = current_user.wallet %>
  <%= @wallet.total_amount %> zł <h3>
</div>
<div class="link"><p><%= link_to 'Powrót', bottles_path %></p></div>